# Generated by Django 5.0.3 on 2024-11-04 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_ID', models.CharField(max_length=200)),
                ('H_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('D_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('D_Experience', models.CharField(blank=True, max_length=200, null=True)),
                ('D_Speciality', models.CharField(blank=True, max_length=200, null=True)),
                ('Availability', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('H_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergencycare.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='ICUVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_ICU', models.IntegerField(blank=True, null=True)),
                ('ICU_Budget', models.IntegerField(blank=True, null=True)),
                ('Vacant', models.CharField(blank=True, max_length=200, null=True)),
                ('H_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencycare.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='Area_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencycare.location'),
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_Number', models.CharField(max_length=200)),
                ('Area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencycare.location')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('S_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('S_Budget', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('H_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergencycare.hospital')),
            ],
        ),
    ]
