# Generated by Django 5.1.2 on 2024-12-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
