# Generated by Django 5.1.2 on 2024-12-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0002_location_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='distance',
        ),
    ]
