# Generated by Django 5.1.2 on 2025-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0003_remove_location_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
