# Generated by Django 5.1.2 on 2025-04-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0004_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuvacancy',
            name='Vacant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
