# Generated by Django 5.1.2 on 2025-04-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0005_alter_icuvacancy_vacant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='longitude',
        ),
    ]
