# Generated by Django 5.1.2 on 2025-04-16 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0006_remove_hospital_latitude_remove_hospital_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_CCU', models.IntegerField(blank=True, null=True)),
                ('CCU_Budget', models.IntegerField(blank=True, null=True)),
                ('Vacant', models.IntegerField(blank=True, null=True)),
                ('H_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencycare.hospital')),
            ],
        ),
    ]
