# Generated by Django 5.1.2 on 2025-04-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0007_ccu'),
    ]

    operations = [
        migrations.CreateModel(
            name='NICU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_NICU', models.IntegerField(blank=True, null=True)),
                ('NICU_Budget', models.IntegerField(blank=True, null=True)),
                ('Vacant', models.IntegerField(blank=True, null=True)),
                ('H_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencycare.hospital')),
            ],
        ),
    ]
