# Generated by Django 5.1.2 on 2025-04-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0008_nicu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NICUBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('baby_condition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nicu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencycare.nicu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
