# Generated by Django 5.1.2 on 2025-04-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0009_nicubooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nicubooking',
            old_name='contact_number',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='nicubooking',
            name='baby_condition',
            field=models.CharField(max_length=100),
        ),
    ]
