# Generated by Django 5.1.2 on 2025-04-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0010_rename_contact_number_nicubooking_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nicubooking',
            name='nicu',
        ),
        migrations.AddField(
            model_name='nicubooking',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
