# Generated by Django 5.1.2 on 2025-04-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0011_remove_nicubooking_nicu_nicubooking_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicubooking',
            name='baby_condition',
            field=models.CharField(choices=[('stable', 'Stable'), ('bad', 'Bad'), ('critical', 'Critical'), ('emergency', 'Emergency')], default='stable', max_length=20),
        ),
        migrations.AlterField(
            model_name='nicubooking',
            name='requirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
