# Generated by Django 5.1.2 on 2025-04-23 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0012_alter_nicubooking_baby_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCUBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('patient_condition', models.CharField(choices=[('stable', 'Stable'), ('bad', 'Bad'), ('critical', 'Critical'), ('emergency', 'Emergency')], default='stable', max_length=20)),
                ('requirements', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
