# Generated by Django 5.1.2 on 2025-04-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0013_ccubooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccubooking',
            name='requirements',
        ),
    ]
