# Generated by Django 5.1.2 on 2025-04-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0014_remove_ccubooking_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicubooking',
            name='baby_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
