# Generated by Django 5.1.2 on 2025-04-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0016_icubooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('burn', 'Burn'), ('cut', 'Cut'), ('fracture', 'Fracture'), ('infection', 'Infection')], max_length=50)),
                ('intensity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major')], max_length=20)),
                ('estimated_budget', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='emergencycare.services')),
            ],
        ),
    ]
