# Generated by Django 5.1.2 on 2025-04-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0017_servicedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='S_Budget',
        ),
    ]
