# Generated by Django 5.1.2 on 2025-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0018_remove_services_s_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
