# Generated by Django 5.1.2 on 2025-04-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0019_alter_servicedetail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='intensity',
            field=models.CharField(max_length=50),
        ),
    ]
