# Generated by Django 5.1.2 on 2025-04-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0020_alter_servicedetail_intensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
    ]
