# Generated by Django 5.1.2 on 2025-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0021_remove_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='Contact_Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
