# Generated by Django 5.1.2 on 2025-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0022_ambulance_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Location_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
