# Generated by Django 5.1.2 on 2025-05-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycare', '0024_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicubooking',
            name='baby_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
